version: '3.7'

services:
  mysqldev:
    container_name: mysqldev
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345678A
      MYSQL_ROOT_PASSWORD: 12345678A
    volumes:
      - mysqldev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - tw7-network 

  web:
    stdin_open: true
    tty: true
    container_name: api-fw7
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 3333
    volumes:
      - ./:/opt/app
    depends_on:
      mysqldev:
        condition: service_healthy 
    ports:
      - '3333:3333'
      - '5555:5555'
    environment:
      PORT: 3333
    healthcheck:
      test: curl --fail backend:3333/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - tw7-network

networks:
  tw7-network:
    name: tw7-network
    driver: bridge
    external: true

volumes:
  mysqldev: